/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/auth/admin-login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/caregiver-login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/caregiver-signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/elderly-login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/elderly-signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/provider-login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/provider-signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/role-select`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/agenda`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/contacts`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/home`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/medications`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/settings`; params?: Router.UnknownInputParams; } | { pathname: `/provider/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/elderly/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/admin-login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/caregiver-login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/caregiver-signup`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/elderly-login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/elderly-signup`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/provider-login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/provider-signup`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/role-select`; params?: Router.UnknownOutputParams; } | { pathname: `/caregiver/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/elderly/agenda`; params?: Router.UnknownOutputParams; } | { pathname: `/elderly/contacts`; params?: Router.UnknownOutputParams; } | { pathname: `/elderly/home`; params?: Router.UnknownOutputParams; } | { pathname: `/elderly/medications`; params?: Router.UnknownOutputParams; } | { pathname: `/elderly/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/elderly/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/provider/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/caregiver/elderly/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/dashboard${`?${string}` | `#${string}` | ''}` | `/auth/admin-login${`?${string}` | `#${string}` | ''}` | `/auth/caregiver-login${`?${string}` | `#${string}` | ''}` | `/auth/caregiver-signup${`?${string}` | `#${string}` | ''}` | `/auth/elderly-login${`?${string}` | `#${string}` | ''}` | `/auth/elderly-signup${`?${string}` | `#${string}` | ''}` | `/auth/provider-login${`?${string}` | `#${string}` | ''}` | `/auth/provider-signup${`?${string}` | `#${string}` | ''}` | `/auth/role-select${`?${string}` | `#${string}` | ''}` | `/caregiver/dashboard${`?${string}` | `#${string}` | ''}` | `/elderly/agenda${`?${string}` | `#${string}` | ''}` | `/elderly/contacts${`?${string}` | `#${string}` | ''}` | `/elderly/home${`?${string}` | `#${string}` | ''}` | `/elderly/medications${`?${string}` | `#${string}` | ''}` | `/elderly/onboarding${`?${string}` | `#${string}` | ''}` | `/elderly/settings${`?${string}` | `#${string}` | ''}` | `/provider/dashboard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/auth/admin-login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/caregiver-login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/caregiver-signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/elderly-login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/elderly-signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/provider-login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/provider-signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/role-select`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/agenda`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/contacts`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/home`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/medications`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/elderly/settings`; params?: Router.UnknownInputParams; } | { pathname: `/provider/dashboard`; params?: Router.UnknownInputParams; } | `/caregiver/elderly/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/caregiver/elderly/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
